

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Button;
                ref class TextBlock;
                ref class ProgressRing;
            }
        }
    }
}

namespace TheByteKitchen
{
    namespace _3D_TV
    {
        partial ref class MainPage : public ::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::Grid^ KinectClientGrid;
            private: ::Windows::UI::Xaml::Controls::Button^ StartStop;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ ErrorMessage;
            private: ::Windows::UI::Xaml::Controls::ProgressRing^ progress;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ LogText2;
        };
    }
}

